mqtt:
  enabled: false

detectors:
  k80:
    type: cpu
    num_threads: 2
    onnx_device: cuda:0

model:
  path: /config/model_cache/yolov8n.onnx
  input_tensor: nchw
  input_pixel_format: bgr
  width: 320
  height: 320
  model_type: yolo-generic

cameras:
  webcam:
    enabled: true
    ffmpeg:
      inputs:
        - path: /dev/video0
          input_args:
            - -f
            - v4l2
            - -input_format
            - mjpeg
          roles:
            - detect
            - record
    
    detect:
      enabled: true
      width: 1920
      height: 1080
      fps: 5
    
    objects:
      track:
        - person
      filters:
        person:
          min_area: 5000
          threshold: 0.7
    
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 2
    
    record:
      enabled: true
      retain:
        days: 2
        mode: motion

detect:
  enabled: true
  width: 1920
  height: 1080
  fps: 5

database:
  path: /config/frigate.db

version: 0.16-0
