
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Letta Bridge REST Commands
rest_command:
  letta_add_memory:
    url: "http://hassistant-letta-bridge:8081/memory/add"
    method: POST
    headers:
      x-api-key: "d6DkfuU7zPOpcoeAVabiNNPhTH6TcFrZ"
      content-type: "application/json"
    payload: >
      {
        "type": "{{ type|default('event') }}",
        "title": "{{ title }}",
        "content": "{{ content }}",
        "tags": {{ tags|default([]) | tojson }},
        "source": {{ source|default([]) | tojson }},
        "confidence": {{ confidence|default(0.7) }},
        "tier": "{{ tier|default('short') }}",
        "pin": {{ pin|default(false) | tojson }},
        "generate_embedding": {{ generate_embedding|default(true) | tojson }}
      }

  letta_memory_maintenance:
    url: "http://hassistant-letta-bridge:8081/memory/maintenance"
    method: POST
    headers:
      x-api-key: "d6DkfuU7zPOpcoeAVabiNNPhTH6TcFrZ"
      content-type: "application/json"

# Letta Bridge Sensors
sensor:
  - platform: rest
    name: letta_daily_brief
    resource: "http://hassistant-letta-bridge:8081/daily_brief"
    method: GET
    headers:
      x-api-key: "d6DkfuU7zPOpcoeAVabiNNPhTH6TcFrZ"
    scan_interval: 900
    value_template: "{{ value_json.items | length if value_json.items is defined else 0 }}"
    json_attributes:
      - since
      - items

# Input text helper for duplicate calendar event detection
input_text:
  last_calendar_event:
    name: Last Created Calendar Event
    max: 255
    initial: ""

# Note: OpenAI Conversation must be configured via UI in Settings > Integrations
# Configure it to use: http://hassistant-glados-orchestrator:8082/v1 with model "glados"

logger:
  default: info
  logs:
    homeassistant.components.assist_pipeline: debug
    homeassistant.components.conversation: debug
