views:
  - title: Speech
    path: speech
    cards:
      - type: entities
        title: Speech Pipeline
        entities:
          - sensor.whisper_stt_health
          - sensor.whisper_stt_latency
          - switch.tts_fallback_wyoming_piper
      - type: history-graph
        title: STT Latency (6h)
        entities:
          - sensor.whisper_stt_latency
        hours_to_show: 6
        refresh_interval: 60
