views:
  - title: Vision Signals
    path: vision-signals
    icon: mdi:eye
    cards:
      - type: horizontal-stack
        cards:
          - type: picture-entity
            entity: camera.vision_screen_stream
            name: Screen Gateway
            camera_view: live
          - type: picture-entity
            entity: camera.vision_realworld_stream
            name: Realworld Gateway
            camera_view: live
      - type: entities
        title: Vision Controls
        entities:
          - switch.vision_on
          - switch.screen_watch_on
          - input_number.vision_threshold
          - input_number.vision_max_frames
      - type: entities
        title: Metrics
        entities:
          - sensor.vl_requests_today
          - sensor.vision_events_ingested
          - sensor.vision_router_queue_depth
          - sensor.vision_router_lock_enabled
          - sensor.vision_router_events_total
          - sensor.vision_router_escalations_total
          - sensor.vision_router_gpu0_util_percent
          - sensor.vision_router_gpu0_mem_free_gb
          - sensor.orchestrator_privacy_paused_total

      - type: entities
        title: Frigate (VM)
        entities:
          - sensor.frigate_version
          - sensor.frigate_uptime
          - sensor.frigate_cpu_percent
          - sensor.frigate_mem_percent

      - type: picture-glance
        title: Room Cam
        entities: []
        camera_image: camera.room_cam
        camera_view: live

      - type: button
        name: Start RTSP Streams
        icon: mdi:video
        tap_action:
          action: call-service
          service: shell_command.start_rtsp_streams
      
      - type: button
        name: Stop RTSP Streams
        icon: mdi:video-off
        tap_action:
          action: call-service
          service: shell_command.stop_rtsp_streams


      - type: history-graph
        title: Queue & Util (last 6h)
        hours_to_show: 6
        refresh_interval: 60
        entities:
          - sensor.vision_router_queue_depth
          - sensor.vision_router_gpu0_util_percent
      - type: markdown
        title: Notes
        content: >
          - Use the switches to gate events at the router.
          - Threshold/Max Frames update the router in real time.
          - Streams pull from the vision gateways' MJPEG endpoints.
