# Memory Integration Package
# Step 2.5: Memory ↔ LLM Integration
# Provides controls and monitoring for the memory system

homeassistant:
  customize:
    sensor.memory_total:
      icon: mdi:database
    sensor.memory_pending:
      icon: mdi:clock-alert
    sensor.memory_recall_hits:
      icon: mdi:bullseye-arrow
    sensor.memory_recall_rate:
      icon: mdi:percent
    sensor.memory_context_chars:
      icon: mdi:text
    switch.memory_autosave:
      icon: mdi:content-save-auto

# Controls
switch:
  - platform: rest
    name: Memory Autosave
    resource: http://letta-bridge:8010/config
    body_on: '{"autosave": true}'
    body_off: '{"autosave": false}'
    is_on_template: "{{ value_json.autosave | default(true) }}"
    headers:
      Content-Type: application/json

input_number:
  memory_min_score:
    name: Memory Recall Threshold
    min: 0.0
    max: 1.0
    step: 0.05
    initial: 0.62
    icon: mdi:target

# Sensors
sensor:
  # Fast-updating sensors (15s interval)
  - platform: rest
    name: Memory Recall Hits
    resource: http://letta-bridge:8010/stats
    value_template: "{{ value_json.last_memory_hits | default(0) }}"
    json_attributes:
      - last_used
      - last_queries
    scan_interval: 15
    timeout: 5

  - platform: rest
    name: Memory Last Used
    resource: http://letta-bridge:8010/stats
    value_template: "{{ value_json.last_used | default(false) }}"
    scan_interval: 15
    timeout: 5

  # Medium-updating sensors (30s interval)
  - platform: rest
    name: Memory Context Chars
    resource: http://orchestrator:8020/metrics
    value_template: >
      {% set lines = value.split('\n') %}
      {% for l in lines %}
        {% if l.startswith('orchestrator_ctx_chars_sum') %}
          {{ l.split(' ')[1]|float|round(0) }}
        {% endif %}
      {% endfor %}
    unit_of_measurement: "chars"
    scan_interval: 30
    timeout: 5

  - platform: rest
    name: Memory Recall Rate
    resource: http://letta-bridge:8010/metrics
    value_template: >
      {% set lines = value.split('\n') %}
      {% set used = 0 %}{% set all = 0 %}
      {% for l in lines %}
        {% if l.startswith('memory_search_total ') %}
          {% set all = l.split(' ')[1]|float %}
        {% endif %}
        {% if l.startswith('memory_search_used_total ') %}
          {% set used = l.split(' ')[1]|float %}
        {% endif %}
      {% endfor %}
      {{ (used / all * 100) if all > 0 else 0 }}
    unit_of_measurement: "%"
    scan_interval: 30
    timeout: 5

  # Slow-updating sensors (60s interval)
  - platform: rest
    name: Memory Total
    resource: http://letta-bridge:8010/stats
    value_template: "{{ value_json.total | default(0) }}"
    json_attributes:
      - embedded
      - pending
    scan_interval: 60
    timeout: 10

# REST commands
rest_command:
  set_memory_config:
    url: http://letta-bridge:8010/config
    method: POST
    headers:
      Content-Type: application/json
    payload: '{"min_score": {{ min_score }}}'

# Automations
automation:
  - id: memory_score_tuning
    alias: Memory - Sync Recall Threshold
    description: Update letta-bridge config when HA slider changes
    trigger:
      - platform: state
        entity_id: input_number.memory_min_score
    action:
      - service: rest_command.set_memory_config
        data:
          min_score: "{{ states('input_number.memory_min_score') | float }}"
