homeassistant:
  customize:
    sensor.whisper_stt_health:
      friendly_name: "Whisper STT Health"
      icon: mdi:robot-outline
    sensor.whisper_stt_latency:
      friendly_name: "STT Latency (avg)"
      icon: mdi:microphone
    switch.tts_fallback_wyoming_piper:
      friendly_name: "Use Fallback TTS"
      icon: mdi:swap-horizontal

sensor:
  - platform: rest
    name: Whisper STT Health
    resource: http://whisper-stt:8000/health
    value_template: "{{ value_json.ok }}"
    json_attributes:
      - model
      - device
      - compute_type
      - vad_filter
      - beam_size
    scan_interval: 30

  - platform: rest
    name: Whisper STT Latency
    resource: http://whisper-stt:8000/metrics
    value_template: >
      {% set sum = 0.0 %}{% set cnt = 0.0 %}
      {% for line in value.split('\n') %}
        {% if line.startswith('whisper_stt_latency_seconds_sum') %}
          {% set sum = line.split(' ')[1] | float %}
        {% elif line.startswith('whisper_stt_latency_seconds_count') %}
          {% set cnt = line.split(' ')[1] | float %}
        {% endif %}
      {% endfor %}
      {{ (sum / (cnt if cnt > 0 else 1)) | round(3) }}
    unit_of_measurement: s
    scan_interval: 30

switch:
  - platform: rest
    name: TTS Fallback (Wyoming Piper)
    resource: http://wyoming-openai:8080/config
    body_on: '{"tts_fallback": true}'
    body_off: '{"tts_fallback": false}'
    is_on_template: "{{ value_json.tts_fallback | default(false) }}"
    headers:
      Content-Type: application/json

binary_sensor:
  - platform: rest
    name: Wyoming Proxy Health
    resource: http://wyoming-openai:8080/healthz
    value_template: "{{ value_json.ok }}"
    scan_interval: 30
