homeassistant:
  customize:
    sensor.memory_total:
      icon: mdi:database
    sensor.memory_pending:
      icon: mdi:clock-alert
    sensor.memory_search_latency:
      icon: mdi:chart-line

sensor:
  - platform: rest
    name: Memory Total
    resource: http://letta-bridge:8010/stats
    method: GET
    value_template: "{{ value_json.total }}"
    json_attributes:
      - embedded
      - pending
      - last_queries
    timeout: 10
    scan_interval: 60
  - platform: rest
    name: Memory Pending
    resource: http://letta-bridge:8010/stats
    method: GET
    value_template: "{{ value_json.pending }}"
    timeout: 10
    scan_interval: 60
  - platform: rest
    name: Memory Search Latency
    resource: http://memory-embed:8001/metrics
    method: GET
    value_template: >
      {% set metrics = value | default('') %}
      {% set sum_matches = metrics | regex_findall('memembed_latency_seconds_sum{route="search"} ([0-9eE\\+\\.-]+)') %}
      {% set count_matches = metrics | regex_findall('memembed_latency_seconds_count{route="search"} ([0-9eE\\+\\.-]+)') %}
      {% set sum = (sum_matches[0] | float(0)) if sum_matches else 0 %}
      {% set count = (count_matches[0] | float(0)) if count_matches else 0 %}
      {{ (sum / count) if count > 0 else 0 }}
    unit_of_measurement: s
    timeout: 10
    scan_interval: 60
  - platform: rest
    name: Memory Additions Today
    resource: http://letta-bridge:8010/metrics
    value_template: >
      {% set total = 0 %}
      {% for line in value.split('\n') %}
        {% if line.startswith('memory_additions_total') %}
          {% set total = total + line.split(' ')[-1]|float(0) %}
        {% endif %}
      {% endfor %}
      {{ total|round(0) }}
    scan_interval: 60

switch:
  - platform: rest
    name: Memory Ingest
    resource: http://letta-bridge:8010/config
    body_on: '{"ingest": true}'
    body_off: '{"ingest": false}'
    is_on_template: "{{ value_json.ingest }}"
    headers:
      Content-Type: application/json
    timeout: 10

button:
  - platform: rest
    name: Memory Backfill Now
    resource: http://letta-bridge:8010/backfill/start
    method: POST
    headers:
      Content-Type: application/json
    payload: '{"source": "homeassistant"}'
    timeout: 15

lovelace:
  dashboards:
    memory:
      mode: yaml
      filename: memory-view.yaml
      title: Memory
      icon: mdi:database
      show_in_sidebar: true
